### ISSUE TITLE
Add a command that reads storage from a deployed contract

### ISSUE THREAD

**Issue by tinchoabbate** [ajsantander/pocketh#44]
It'd be nice to do something like: `pocketh query-storage <contract-address> <storage-slot>`. Super useful to read deployed proxies' storage (where Etherscan is not useful at all).

**Comment by elopio** [comment]
Also to read non-public state variables. +1.

**Comment by ajsantander** [comment]
@tinchoabbate great idea! Thx.

I've implemented a new `storage` command in v0.1.27.
Also, I'll be working on a more advanced command that is able to retrieve all the storage of a contract analyzing the ast, printing out not only the values stored at each storage but the values stored at each variable, parsing types. Not sure if its even possible but I'll give it a try.
https://github.com/ajsantander/pocketh/issues/46
