### ISSUE TITLE
Cannot read 'nodes' parameter in compiled contract. 

### ISSUE THREAD

**Issue by nikeshnazareth** [ajsantander/pocketh#61]
I compiled the [ANT token](https://etherscan.io/address/0x960b236a07cf122663c4303350609a66a7b288c0#code) with `truffle compile` and solc 0.4.9 to produce and `ANT.json` file. Note: it was originally compiled with 0.4.8 but that is too old for the latest version of truffle. I don't know if that is an issue.

When I run 

`pocketh liststorage mainnet ANT.json 0x960b236A07cf122663c4303350609A66A7B288C0`

I get the result

> TypeError: Cannot read property 'nodes' of undefined

**Comment by ajsantander** [comment]
Hmm... It seems that this version of solcjs (0.4.9) doesn't output any AST data :thinking: 
I tried a few higher patches and the same thing happens. However, 0.4.25 does seem to do so.

I added an error when the AST data is not found.

**Comment by ajsantander** [comment]
If you use liststorage with artifacts compiled with solc 0.4.25, you don't get that error... however, since liststorage cannot handle inheritance yet #50, the command doesn't output anything :disappointed: 

I'm closing this issue anyway because it doesn't seem to be a problem with pocketh.

**Comment by ajsantander** [comment]
For now, I recommend that you use the members command with the inherited option, and search the list from bottom to top, looking for variables. Then you can use the storage command to read elements manually. In the near future, liststorage should be able to do this exact same process programmatically.
