### ISSUE TITLE
members command fails on astUtil 

### ISSUE THREAD

**Issue by alcuadrado** [ajsantander/pocketh#80]
Hey Ale! I found a bug in one of the commands.

I'm trying to run this `npx pocketh members  build/contracts/ERC721Base.json`, and getting this output:

```
¬ ERC721Base
astUtil does not now how to convert node type UsingForDirective to string.
```

This is the code I'm using: https://github.com/ripio/rcn-network/tree/c439b94851d3af5217c6c1c6b5bf6f940676a383

And some info about my environment:

```
% node --version
v8.15.1
% npx pocketh --version
0.1.43
```

**Comment by ajsantander** [comment]
Thx!
Fixed in 0.1.44, astUtil can now parse `UsingForDirective` AST nodes. 
Also, not throwing when astUtil doesn't understand how to parse a node to string, just warning =P
