### ISSUE TITLE
Add a command that retrieves code from Etherscan, given an address

### ISSUE THREAD

**Issue by tinchoabbate** [ajsantander/pocketh#86]
I coded a simple script to single out Solidity contracts, that are flattened in one file, into multiple separate files: https://github.com/tinchoabbate/solidity-splitter

I mainly use it when I need to locally audit deployed stuff with verified source-code in Etherscan. It'd be really nice if we had it integrated in Pocketh! Could work either by providing the contract's address and fetching the verified code from Etherscan through the API, or for a local file as well. You can see my implementation in Python for some inspiration - it's rather naive (counting open and closing braces) and could be greatly improved probably, but it works.

**Comment by ajsantander** [comment]
For the record, I studied the possibility of using compiler output to split the source files, but it wasn't a good idea xD

I'd split this feature request into two commands:
1) A command that retrieves the source code from etherscan
2) A command that splits a unified source code file into separate files, one per contract

So I'll rename this feature request and create the other one.

**Comment by alcuadrado** [comment]
I love this idea @tinchoabbate 😍!

**Comment by ajsantander** [comment]
Both commands implemented (`getcode` and `split`) in v0.1.52.
Was so easy to implement with your script @tinchoabbate , thxxxxx!
